### Getting SCHEMA
POST http://127.0.0.1:8080/
Content-Type: application/json
correlation_id: {{$uuid}}

{"query":"{ _service { sdl } }"}

### Getting Customer
POST http://127.0.0.1:8080/
Content-Type: application/json
correlation_id: {{$uuid}}

{"query":"{ customer(id: \"CUSTOMER_1\") {id name }} "}

###