# curl -X POST http://127.0.0.1:8081/
#-H 'content-type: application/json'
#--data '{"query":"{ _service { sdl } }"}'
POST http://127.0.0.1:8081/
Content-Type: application/json

{"query":"{ _service { sdl } }"}

###