server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    jaeger:
      protocols:
        thrift_http: {}
        grpc: {}

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  trace_idle_period: 10s
  max_block_bytes: 1048576   # 1MB
  max_block_duration: 5m

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095

query_frontend:
  max_outstanding_per_tenant: 1000
  search:
    max_duration: 0

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/traces