{
 "title": "Graph-Bank",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Customer",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"graph-customer\"} |= `TRACE_ID`"
    }
   ]
  },
  {
   "title": "Deposit",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"graph-deposit\"} |= `TRACE_ID`"
    }
   ]
  },
  {
   "title": "GRAPH CALLS",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service=\"graph-customer\"} |= `TRACE_ID` [$__auto])",
     "legendFormat": "graph-customer"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({service=\"graph-deposit\"} |= `TRACE_ID` [$__auto])",
     "legendFormat": "graph-deposit"
    }
   ]
  }
 ]
}