apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      derivedFields:
        - name: trace_id
          matcherType: regex
          matcherRegex: '"trace_id"\s*:\s*"([^"]+)"'
          datasourceUid: TEMPO_DS
          url: '$${__value.raw}'